export const ICONS = {
  record: "/assets/icons/record.svg",
  close: "/assets/icons/close.svg",
  upload: "/assets/icons/upload.svg",
};

export const dummyCards: VideoCardProps[] = [
  {
    id: "1",
    title: "Building a Modern Navbar in Next.js",
    thumbnail: "/assets/samples/thumbnail (1).png",
    createdAt: new Date("2025-01-02"),
    userImg: "/assets/images/jason.png",
    username: "jason",
    views: 1234,
    visibility: "public",
    duration: 150, // seconds
  },
  {
    id: "2",
    title: "Tailwind CSS Layout Masterclass",
    thumbnail: "/assets/samples/thumbnail (2).png",
    createdAt: new Date("2025-01-05"),
    userImg: "/assets/images/sarah.png",
    username: "sarah_dev",
    views: 8945,
    visibility: "public",
    duration: 420,
  },
  {
    id: "3",
    title: "Next.js App Router Crash Course",
    thumbnail: "/assets/samples/thumbnail (3).png",
    createdAt: new Date("2025-01-10"),
    userImg: "/assets/images/alex.png",
    username: "alex_codes",
    views: 3421,
    visibility: "private",
    duration: 305,
  },
  {
    id: "4",
    title: "Understanding React Server Components",
    thumbnail: "/assets/samples/thumbnail (4).png",
    createdAt: new Date("2025-01-14"),
    userImg: "/assets/images/emily.png",
    username: "emily_ui",
    views: 210,
    visibility: "private",
    duration: 185,
  },
  {
    id: "5",
    title: "Deploying Your First SaaS App",
    thumbnail: "/assets/samples/thumbnail (5).png",
    createdAt: new Date("2025-01-18"),
    userImg: "/assets/images/david.png",
    username: "david_saas",
    views: 15678,
    visibility: "public",
    duration: 600,
  },
  {
    id: "6",
    title: "React Performance Optimization Techniques",
    thumbnail: "/assets/samples/thumbnail (6).png",
    createdAt: new Date("2025-01-21"),
    userImg: "/assets/images/jessica.png",
    username: "jessica_perf",
    views: 4320,
    visibility: "public",
    duration: 275,
  },
  {
    id: "7",
    title: "Designing Scalable UI Systems",
    thumbnail: "/assets/samples/thumbnail (7).png",
    createdAt: new Date("2025-01-25"),
    userImg: "/assets/images/lisa.png",
    username: "lisa_design",
    views: 980,
    visibility: "private",
    duration: 360,
  },
  {
    id: "8",
    title: "Full-Stack Authentication with NextAuth",
    thumbnail: "/assets/samples/thumbnail (8).png",
    createdAt: new Date("2025-01-28"),
    userImg: "/assets/images/michael.png",
    username: "michael_stack",
    views: 12750,
    visibility: "public",
    duration: 540,
  },
];


export const MAX_FILE_SIZE = 500 * 1024 * 1024; // 500 MB
export const MAX_THUMBNAIL_SIZE = 10 * 1024 * 1024; // 10 MB